### ISSUE TITLE
Accounts

### ISSUE THREAD

**Issue by FernandoVinha** [FernandoVinha/ISO17025#6]
### This module handles the management of user accounts, companies, and contacts. It ensures that users are assigned correct roles and permissions, and allows for the management of company and contact data.

- [x] **User Roles:** Create and assign user roles, such as client, supplier, or employee.

- [x] **Company Management:** Manage company profiles, including contact details, company relationships, and profile images.

- [x] **Contact Management:** Create and manage contacts associated with companies, including their position and contact information.

- [x] **Permission Management:** Implement and enforce role-based permissions for creating, editing, and viewing accounts, companies, and contacts.

- [x] **Invitation System:** Generate and manage invitation links to allow new users to register on the platform.

- [x] **Historical Records:** Track all changes made to user accounts, companies, and contacts for auditing purposes.

**Comment by caarol985** [comment]
## 1. Accounts Management

### Relationship Types
- We want to have a table or a way to register different types of relationships. For example, we might want to store things like 'friend,' 'colleague,' 'partner,' or something similar.
- We also need a way to track who created or changed these records, you know? A history to keep track of who did what.
- And oh, we need some controls so that only certain people can create or edit these relationship types, like a permissions system.

### Custom Users
- We’ll need a user registration system, but we want something a bit more specific than just "name and password."
- We want each user to have a unique email, which will be used for logging in to our application.
- In addition to that, we need basic information like the user's first and last name, a profile image (because, well, everything has photos these days), and the role they play, like whether they're a client, supplier, maintenance staff, or just a regular employee.
- Also, we need a way to distinguish who can do administrative tasks, like managing the system, from regular users.
- These users should also have a way to be deactivated (in case we need to block someone) and have a date of when they were created.

### Invitation System
- We want a feature to send email invitations for people to sign up.
- Like, someone will input the person's email, and the system will generate a token (a kind of random key) to ensure the invitation is valid.
- It would be nice if we could track when the invitation was created and whether it has been used or not.
